dist: trusty
language: php
php:
- 7.1
- 7.2
- 7.3
- 7.4
addons:
  sonarcloud:
    organization: "dragonbe-github" # the key of the org you chose at step #3
    token:
      secure: "tSNywFsYthwLQc89JpDthdVgU91E6A5VYs1n95FC5hPWZZxc6kYCkLAA6dD8pLi0BRTx5zStWN6IAdH0sB5xgexeu5lBAuyDr66v3B/TtPMyXyD5YIUbb0JyylA3rW45lSOqUV439Qhniqyu59VD7HCeCS8B64k7XW9tOGcL4yc="

# CodeClimat settings
env:
  global:
    - CC_TEST_REPORTER_ID=54bede52e30ba07a150007dc

before_script:
  - composer install --prefer-source --no-interaction
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - mkdir -p build/logs
  - vendor/bin/phpcs
  - vendor/bin/phpunit
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then sonar-scanner; fi'
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

cache:
  directories:
    - '$HOME/.sonar/cache'

